# The app's name, which must be unique within the project.
name: "marcos-nuxt-project"

# The language and version for your app.
type: "nodejs:24"

# The size of the app's persistent disk (in MB).
disk: 2048

# The app's configuration when it's exposed to the web.
web:
  commands:
    start: npm start
  locations:
    "/":
      # The public directory relative to the app root.
      root: "public"
      # Forward resources to the app.
      passthru: true
      # What files to use when serving a directory.
      index: ["index.html"]
      # Allow files even without specified rules.
      allow: true
